[Server]
server.ip=127.0.0.1
server.port=37120
server.private.port=37119
server.class.path=org.alexdev.roseau.server.netty.NettyServer

[Database]
type=jdbc
db.hostname=127.0.0.1
db.username=root
db.password=123
db.database=roseau

[Logging]
log.errors=true
log.output=true
log.connections=true
log.packets=true

